### ISSUE TITLE
Standalone PHP version

### ISSUE THREAD

**Issue by rilwis** [isaumya/wp-server-stats#6]
Hi, your plugin is really interesting. But as I host many websites on a same VPS, I'd like to ask if you can make this plugin a standalone PHP version, so I can just install on my VPS once and access to that to see all the information about the server.

This also helps if I want to restrict the access to this info privately.

Thanks.

**Comment by isaumya** [comment]
Hi @rilwis,
In the initial days, I had created just a PHP only script for purpose like these. But unfortunately, there wasn't much market interest in it so I didn't maintain it any longer. That is why currently only the WordPress version is available as it has a good response. I hope you will understand.

With the WordPress version also you can keep things private as only admins can see the details.
